using UnityEngine;
using UnityEngine.Tilemaps;

// Auto-generated by the Kenney tilesheet tool. A Tile that also carries gameplay
// metadata. Collision is the base Tile's colliderType (None/Sprite/Grid); these
// fields describe behaviour. Solid tiles use Grid (full-cell box); ramps and
// one-way platforms use Sprite, so the collider follows the sprite outline.
//
// ONE-WAY PLATFORMS (oneWay == true, e.g. bridge / *_cloud / lab_platform_* /
// platform_lab_*): the Sprite collider is only a thin ledge. To make it
// pass-through-from-below, put these tiles on their OWN Tilemap and add, on that
// Tilemap GameObject:
//   TilemapCollider2D  -> Used By Composite = true
//   Rigidbody2D        -> Body Type = Static
//   CompositeCollider2D-> Used By Effector = true
//   PlatformEffector2D -> Use One Way = true (Surface Arc ~180, pointing up)
// Keep solid tiles on a separate Tilemap so the effector only affects platforms.
[CreateAssetMenu(fileName = "GameplayTile", menuName = "Kenney/Gameplay Tile")]
public class GameplayTile : Tile
{
    public string category;
    public bool solid;
    public bool damagesPlayer;
    public int damage;
    public bool collectible;
    public bool climbable;
    public bool oneWay;
    public bool bouncy;
    public bool breakable;
    public bool interactive;
    public bool liquid;
}
